hyperskill_project:
  id: 89
  ide_files: https://stepik.org/media/attachments/lesson/271583/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Wed, 20 Oct 2021 14:44:28 UTC
stages:
- id: 494
  step: 7817
  is_completed: true
- id: 495
  step: 7818
  is_completed: false
- id: 496
  step: 7819
  is_completed: false
- id: 497
  step: 7820
  is_completed: false
- id: 498
  step: 7821
  is_completed: false
- id: 499
  step: 7822
  is_completed: false
topics:
  0:
  - title: Binary numbers
    theory_id: 5544
  - title: Hexadecimal numbers
    theory_id: 8788
  - title: Units of information
    theory_id: 6865
  - title: Computer algorithms
    theory_id: 4953
  - title: Computer programming
    theory_id: 8739
  - title: Introduction to Kotlin
    theory_id: 4350
  - title: Basic literals
    theory_id: 4351
  - title: Overview of the basic program
    theory_id: 4362
  - title: Values and variables
    theory_id: 4371
  - title: Data types
    theory_id: 4388
  - title: The classification of basic types
    theory_id: 4455
  - title: Standard output
    theory_id: 4425
  - title: Arithmetic operations
    theory_id: 4472
  - title: Boolean and logical operations
    theory_id: 4515
  - title: Increment and decrement
    theory_id: 10776
  - title: Ordering and total order
    theory_id: 9253
  - title: Ordering of compound objects
    theory_id: 9457
  - title: Functions
    theory_id: 13884
  - title: Invoking functions
    theory_id: 4575
  - title: Standard input
    theory_id: 4445
  - title: Type conversion
    theory_id: 4672
  - title: Reading data with a readLine
    theory_id: 11224
  - title: Objects
    theory_id: 11233
  - title: Type of the numeric expression
    theory_id: 9506
  - title: Integers in action
    theory_id: 4488
  - title: Relational operators
    theory_id: 4525
  - title: Equality
    theory_id: 11236
  - title: String basics
    theory_id: 12553
  - title: String templates
    theory_id: 4547
  - title: If expression
    theory_id: 4625
  - title: Repeating blocks
    theory_id: 4643
  - title: Unicode
    theory_id: 7899
  - title: Characters
    theory_id: 4680
  - title: Working with strings
    theory_id: 12561
  - title: Getting substrings
    theory_id: 8535
  - title: Ranges
    theory_id: 4633
  - title: For loop and ranges
    theory_id: 4652
  - title: Mutable list
    theory_id: 14879
  - title: Work with MutableLists
    theory_id: 14902
  - title: For loop and lists
    theory_id: 15022
  - title: Processing strings
    theory_id: 9027
  1:
  - title: IDE
    theory_id: 10996
  - title: The big O notation
    theory_id: 13991
  - title: IntelliJ IDEA
    theory_id: 3801
  - title: IDEA Basics
    theory_id: 5819
  - title: EduTools
    theory_id: 5839
  - title: Searching problem
    theory_id: 15894
  - title: Linear search
    theory_id: 4970
  2:
  - title: Comments
    theory_id: 4406
  - title: Coding style conventions
    theory_id: 4419
  - title: Naming variables
    theory_id: 4389
  - title: Declaring functions
    theory_id: 4580
  - title: While loops
    theory_id: 4659
  - title: When expression
    theory_id: 4631
  - title: Jumps and returns
    theory_id: 6165
  3:
  - title: Introduction to operating systems
    theory_id: 9704
  - title: Files
    theory_id: 13025
  - title: Functions as objects
    theory_id: 5991
  - title: Lambda expressions
    theory_id: 6154
  - title: Command line overview
    theory_id: 8977
  - title: Parameters and options
    theory_id: 9746
  - title: Arrays
    theory_id: 4564
  - title: String arrays
    theory_id: 11477
  - title: The main() function
    theory_id: 10484
  - title: IntelliJ Run Configurations
    theory_id: 10630
  - title: Reading files
    theory_id: 6351
  - title: Errors in programs
    theory_id: 11559
  - title: What is an exception
    theory_id: 7243
  4:
  - title: Introduction to collections
    theory_id: 10390
  - title: List
    theory_id: 10730
  - title: Mutable List
    theory_id: 11032
  - title: Map
    theory_id: 12659
  - title: Mutable Map
    theory_id: 15876
  5:
  - title: Introduction to OOP
    theory_id: 3614
  - title: Declaring classes
    theory_id: 6200
  - title: Functional decomposition
    theory_id: 12668
  - title: Default arguments
    theory_id: 4637
  - title: Named arguments
    theory_id: 4640
  - title: Constructors
    theory_id: 10740
  - title: Member functions
    theory_id: 6364
  - title: Object declarations
    theory_id: 10698
  - title: Companion object
    theory_id: 10707
  - title: Enum
    theory_id: 6245
